### ISSUE TITLE
Segfault error

### ISSUE THREAD

**Issue by Notupus** [Lutzion/openwrt-dsl-statistics#1]
`[356576.256109] do_page_fault(): sending SIGSEGV to rrdtool for invalid read access from 00000168
[356576.263343] epc = 77dbb57f in librrd.so.0.0.0[77d94000+40000]
[356576.270053] ra  = 77dbb571 in librrd.so.0.0.0[77d94000+40000]`
Instructions for installation unclear or script is broken or both. Can you publish more clear instructions so that I can try and see if I did something wrong.

**Comment by Lutzion** [comment]
To find out, why there is the issue, check the following:

do you use openwrt 21.02-rc1?
The scripts are only tested for this release. 

Write the entry
`* * * * * /etc/init.d/dsl_control dslstat > /tmp/dslstat.txt`
to crontab (system - scheduled tasks)
Be sure to have a comment as last line.

restart the job `cron`  in system - startup.
Wait at least one minute to let the script being called once.

Check if the file `/tmp/dslstat.txt` exists.
If so, check if it includes json formated infos like 
`{   
	"api_version": "4.17.18.6",   
	"firmware_version": "5.8.1.5.0.7",   
	"chipset": "Lantiq-VRX200",   
	"driver_version": "1.5.17.6",   
       ...`   

Copy the script `dsl_stats.sh` to `/yourfolder/dsl_stats.sh` 
and make it executable for everybody!

Then go to statistics - setup, enable the plugin exec and add a record:
 `/yourfolder/dsl_stats.sh` nobody nogroup and save that.
where `/yourfolder` should be replaced with an actual existing folder in both cases
but like i wrote: not in tmp folder as it does not survive reboot.

Then copy (or append the code in editor) `exec.js` to `/www/luci-static/resources/statistics/rrdtool/definitions/`

After that restart the jobs `collectd` and `luci-statistics` in system - startup.

I hope you will find a missing step.
Please let me know which step - if so - corrected the function or if you use another openwrt version.

**Comment by Notupus** [comment]
> 
> 
> To find out, why there is the issue, check the following:
> 
> do you use openwrt 21.02-rc1?
> The scripts are only tested for this release.
> 
> Write the entry
> `* * * * * /etc/init.d/dsl_control dslstat > /tmp/dslstat.txt`
> to crontab (system - scheduled tasks)
> Be sure to have a comment as last line.
> 
> restart the job `cron` in system - startup.
> Wait at least one minute to let the script being called once.
> 
> Check if the file `/tmp/dslstat.txt` exists.
> If so, check if it includes json formated infos like
> `{ "api_version": "4.17.18.6", "firmware_version": "5.8.1.5.0.7", "chipset": "Lantiq-VRX200", "driver_version": "1.5.17.6", ...`
> 
> Copy the script `dsl_stats.sh` to `/yourfolder/dsl_stats.sh`
> and make it executable for everybody!
> 
> Then go to statistics - setup, enable the plugin exec and add a record:
> `/yourfolder/dsl_stats.sh` nobody nogroup and save that.
> where `/yourfolder` should be replaced with an actual existing folder in both cases
> but like i wrote: not in tmp folder as it does not survive reboot.
> 
> Then copy (or append the code in editor) `exec.js` to `/www/luci-static/resources/statistics/rrdtool/definitions/`
> 
> After that restart the jobs `collectd` and `luci-statistics` in system - startup.
> 
> I hope you will find a missing step.
> Please let me know which step - if so - corrected the function or if you use another openwrt version.

I don't use owrt 21.02 I use master cause the DSA changes are too awesome to wait for them to merge. It was permission errors and crontab not being restarted, I made a pull request feel free to either merge or change it yourself.
